# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later
name: macOS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Install MoltenVK
      run: |
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        arch -x86_64 /usr/local/bin/brew install molten-vk
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=x86_64
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(sysctl -n hw.ncpu)
    - name: Retrieve Git Hash
      id: git-hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Package
      run: |
        mkdir upload
        mv ${{github.workspace}}/build/shadps4 upload
        cp $(arch -x86_64 /usr/local/bin/brew --prefix)/opt/molten-vk/lib/libMoltenVK.dylib upload
        install_name_tool -add_rpath "@loader_path" upload/shadps4
        tar cf shadps4-macos-sdl-${{ steps.git-hash.outputs.hash }}.tar.gz -C upload .
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: shadps4-macos-sdl-${{ steps.git-hash.outputs.hash }}
        path: shadps4-macos-sdl-${{ steps.git-hash.outputs.hash }}.tar.gz