# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -T ClangCL

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Retrieve Git Hash
      id: git-hash
      shell: cmd
      run: |
        FOR /F "tokens=*" %%g IN ('git rev-parse --short HEAD') do (SET HASH=%%g)
        echo hash=%HASH% >> %GITHUB_OUTPUT%

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: shadps4-win64-sdl-${{ steps.git-hash.outputs.hash }}
        path: |
          ${{github.workspace}}/build/Release/shadPS4.exe